Fix flaky spec (maybe)
failing spec: modules/reporting/spec/features/me_value_spec.rb:37
failing runs:
  - https://github.com/opf/openproject/actions/runs/20822981695/job/59816423092?pr=21576
  - https://github.com/opf/openproject/actions/runs/20820798487/job/59816852049?pr=21585
  - https://github.com/opf/openproject/actions/runs/20842664090/job/59879938099?pr=21561

It fails with the following error:

    Failure/Error: expect(element).to have_css(".ng-value .ng-value-label", text: value, wait: 10)

    Ferrum::JavaScriptError:
      TypeError: within.querySelectorAll is not a function
          at Cuprite.find (<anonymous>:27:37)
          at <anonymous>:1:31

Looking into it, it seems that the cuprite node object is no longer
referring to the correct browser element: the reference is help in a
nodeId. When getting the element for that nodeId, it gets a comment
object, and this one does not have a querySelectorAll function, hence
the error.

It looks like the nodeId got staled and was not tracked by
cuprite/ferrum.

The attemptive fix is to refresh the user_autocompleter value to have a
correct reference to the browser element and avoid the issue.

Not sure why this error only happens now as we did not upgrade cuprite
nor ferrum recently. Maybe a change in chrome internals?