Fix attempt for flakly cost reports feature spec
Using the same `Capybara::Node::Element` handle after a page navigation
is unsafe. The Node is detached and may no longer exist in the DOM.

Unfortunately Ferrum doesn't rethrow errors with helpful messages, hence
this obscure error:

      TypeError: within.querySelectorAll is not a function
          at Cuprite.find (<anonymous>:27:37)
          at <anonymous>:1:31